from __future__ import annotations

from typing import Any, Protocol


class DeviceTransport(Protocol):
    def configure(self) -> None: ...

    def send_command(self, command: str) -> Any: ...

    def set_mappings(self, command_map: dict[str, Any], property_map: dict[str, Any]) -> None: ...  # optional

    def get_monitor(self) -> Any: ...

    def refresh_monitor(self) -> Any: ...

    def get_properties(self) -> Any: ...

    def get_property(self, name: str) -> Any: ...

    def health(self) -> Any: ...
